export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'

export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const FETCH_LOADING = "FETCH_LOADING"
export const FETCH_ERROR = "FETCH_ERROR"
export const FETCH_JOBS_ID_SUCCESS = "FETCH_JOBS_ID_SUCCESS"
export const COUNT_TOTAL_SEARCH_RESULT = "COUNT_TOTAL_SEARCH_RESULT"
export const SET_PAGE = "SET_PAGE"
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"


export const LOGOUT = 'LOGOUT'